# Generated by Django 5.1.1 on 2025-02-16 10:47

import django.db.models.deletion
import slth
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Cor",
                "verbose_name_plural": "Cor",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    slth.db.models.ImageField(upload_to="images", verbose_name="Foto"),
                ),
                (
                    "verso",
                    slth.db.models.ImageField(
                        blank=True, null=True, upload_to="images", verbose_name="Verso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "latitude",
                    slth.db.models.CharField(max_length=255, verbose_name="Latitulde"),
                ),
                (
                    "longitude",
                    slth.db.models.CharField(max_length=255, verbose_name="Longitude"),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locais",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="TipoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Tipo de Veículo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Veículo",
                "verbose_name_plural": "Tipos de Veículo",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "marca",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.marca",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "cpf_cnpj",
                    slth.db.models.CharField(max_length=255, verbose_name="CPF/CNPJ"),
                ),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "documento",
                    slth.db.models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.documento",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Estampador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", slth.db.models.CharField(max_length=255, verbose_name="CNPJ")),
                ("nome", slth.db.models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "locais_instalacao",
                    slth.db.models.OneToManyField(
                        to="api.local", verbose_name="Locais de Instalação"
                    ),
                ),
                (
                    "operadores",
                    slth.db.models.ManyToManyField(
                        to="api.pessoa", verbose_name="Operadores"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estampador",
                "verbose_name_plural": "Estampadores",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
        migrations.CreateModel(
            name="Emplacamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    slth.db.models.DateTimeField(
                        auto_created=True, verbose_name="Data/Hora de Início"
                    ),
                ),
                (
                    "data_conclusao",
                    slth.db.models.DateTimeField(
                        null=True, verbose_name="Data/Hora de Conclusão"
                    ),
                ),
                (
                    "foto_operador",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto do Operador",
                    ),
                ),
                (
                    "latitude",
                    slth.db.models.CharField(
                        max_length=255, null=True, verbose_name="Latitulde"
                    ),
                ),
                (
                    "longitude",
                    slth.db.models.CharField(
                        max_length=255, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "numero_placa",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Número do Placa"
                    ),
                ),
                (
                    "zero_kilometro",
                    models.BooleanField(blank=True, verbose_name="Zero Kilômetro"),
                ),
                (
                    "numero_chassi",
                    slth.db.models.CharField(
                        max_length=255, verbose_name="Número do Chassi"
                    ),
                ),
                (
                    "foto_chassi",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto do Chassi",
                    ),
                ),
                (
                    "foto_dianteira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto Dianteira",
                    ),
                ),
                (
                    "foto_traseira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto Traseira",
                    ),
                ),
                (
                    "foto_placa_dianteira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto da Placa Dianteira",
                    ),
                ),
                (
                    "foto_placa_traseira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto da Placa Traseira",
                    ),
                ),
                (
                    "foto_segunda_placa_traseira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto da Segunda Placa Traseira",
                    ),
                ),
                (
                    "foto_descarte_placa_dianteira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto do Descarte da Placa Dianteira",
                    ),
                ),
                (
                    "foto_descarte_placa_traseira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto do Descarte da Placa Traseira",
                    ),
                ),
                (
                    "foto_descarte_segunda_placa_traseira",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto do Descarte da Segunda Placa Traseira",
                    ),
                ),
                (
                    "foto_procuracao",
                    slth.db.models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Foto da Procuração",
                    ),
                ),
                (
                    "cor",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cor",
                        verbose_name="Cor",
                    ),
                ),
                (
                    "estampador",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.estampador",
                        verbose_name="Estampador",
                    ),
                ),
                (
                    "modelo",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.modelo",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "operador",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pessoa",
                        verbose_name="Operador",
                    ),
                ),
                (
                    "proprietario",
                    slth.db.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2",
                        to="api.pessoa",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "representante",
                    slth.db.models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p3",
                        to="api.pessoa",
                        verbose_name="Representante",
                    ),
                ),
                (
                    "tipo_veiculo",
                    slth.db.models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tipoveiculo",
                        verbose_name="Tipo de Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emplacamento",
                "verbose_name_plural": "Emplacamentos",
            },
            bases=(models.Model, slth.ModelMixin),
        ),
    ]
