# Generated by Django 5.1.1 on 2025-02-17 09:33

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_emplacamento_autorizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emplacamento",
            name="foto_boletim_ocorrencia",
            field=slth.db.models.ImageField(
                blank=True,
                null=True,
                upload_to="images",
                verbose_name="Foto do Boletim de Ocorrência",
            ),
        ),
        migrations.AlterField(
            model_name="emplacamento",
            name="operador",
            field=slth.db.models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.pessoa",
                verbose_name="Operador",
            ),
        ),
    ]
