# Generated by Django 5.1.1 on 2025-02-18 17:43

import django.db.models.deletion
import slth.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_cor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emplacamento",
            name="operador",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.pessoa",
                verbose_name="Operador",
            ),
        ),
    ]
