# Generated by Django 5.1.1 on 2025-02-19 20:47

import django.db.models.deletion
import slth.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_emplacamento_operador"),
    ]

    operations = [
        migrations.AddField(
            model_name="emplacamento",
            name="leiloado",
            field=models.BooleanField(default=False, verbose_name="Leiloado?"),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="qrcode_placa_dianteira",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="QrCode da Placa Dianteira",
            ),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="qrcode_placa_traseira",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="QrCode da Placa Traseira",
            ),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="qrcode_segunda_placa_traseira",
            field=slth.db.models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="QrCode da Segunda Placa Traseira",
            ),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="segunda_placa_traseira",
            field=models.BooleanField(
                default=False, verbose_name="Segunda Placa Traseira?"
            ),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="terceiro_interessado",
            field=slth.db.models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="p4",
                to="api.pessoa",
                verbose_name="Terceiro Interessado",
            ),
        ),
        migrations.AddField(
            model_name="emplacamento",
            name="via_procuracao",
            field=models.BooleanField(default=False, verbose_name="Via Procuração?"),
        ),
        migrations.AlterField(
            model_name="emplacamento",
            name="zero_kilometro",
            field=models.BooleanField(blank=True, verbose_name="Zero Kilômetro?"),
        ),
    ]
